Integrate clang plugin into kernel build
yale-systems/freebsd-src pull request #10
Opened 2024-09-23 13:01 UTC by BrianChoi12

Modify ctf convert macro so that the build runs the clang plugin as well, using a script that filters to only run on C source code files.

2024-09-23 15:44 UTC, gvnn3 requested changes

2024-09-23 15:44 UTC, gvnn3 commented on sys/conf/kern.pre.mk
So...now that you have this working in your branch, the next thing to do is to add a new CTFCONVERT like option rather than to convert the CTF thing to our new call.  Can you do that and then add that to this PR?

2024-10-08 15:28 UTC, BrianChoi12 commented on sys/conf/kern.pre.mk
I decoupled table extract from CTFCONVERT to make it its own thing, is this what you had in mind? One thing to note is that the table extractor in its current form runs on every run of the build, would it be better to make some sort of build option to determine whether it should run or not?

2024-10-11 16:34 UTC, gvnn3 approved these changes
I'm going to pull this into our dev branch now.  Thanks @BrianChoi12 !

2024-10-11 16:40 UTC, merged